name: (tModLoader) Get new releases

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        year: [ 2025, 2026 ]
        prerelease: [ true, false ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Get releases
        run: |
          curl -s https://api.github.com/repos/tModLoader/tModLoader/releases > output.txt
          echo CHECK_VER="$(
            jq -r \
              --arg YEAR "${{ matrix.year }}" \
              --argjson PRE "${{ matrix.prerelease }}" \
              '[.[]
                | select(.tag_name | contains($YEAR))
                | select(.prerelease == $PRE)
              ]
              | max_by(.published_at)?
              | .tag_name
              | sub("^v";"")
              // ""' \
              output.txt
          )" >> "$GITHUB_ENV"

      - name: Check release
        run: |
          YEAR="${{ matrix.year }}"
          PRE="${{ matrix.prerelease }}"
          VERSION=${{ env.CHECK_VER }}
          if [ -n "$VERSION" ]; then
            UPSTREAM=$(curl -s "https://hub.docker.com/v2/repositories/passivelemon/terraria-docker/tags/tmodloader-${VERSION}")

            if echo "$UPSTREAM" | jq -e ".digest" > /dev/null; then
              echo "$VERSION is already published." >> "$GITHUB_STEP_SUMMARY"
              VERSION=false
            else
              echo "$VERSION is not already published." >> "$GITHUB_STEP_SUMMARY"
            fi
          else
            echo "A $YEAR (pre: $PRE) version does not exist." >> "$GITHUB_STEP_SUMMARY"
            VERSION=false
          fi

          jq -n \
            --arg YEAR "$YEAR" \
            --arg PRE "$PRE" \
            --arg VERSION "$VERSION" \
            '{"year": {($YEAR): {"prerelease": {($PRE): $VERSION}}}}' > "${YEAR}-${PRE}.json"

      - name: Upload json fragment
        uses: actions/upload-artifact@v7
        with:
          name: "${{ matrix.year }}-${{ matrix.prerelease }}"
          path: "${{ matrix.year }}-${{ matrix.prerelease }}.json"

  data_handler:
    needs: check
    runs-on: ubuntu-latest
    outputs:
      data: ${{ steps.write_output.outputs.data }}
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v8
        with:
          path: output/

      - name: Merge json fragments
        run: |
          jq -sc 'reduce .[] as $item ({}; . * $item)' output/*/*.json > final-data.json

      - name: Upload final-data.json
        uses: actions/upload-artifact@v7
        with:
          name: final-data
          path: final-data.json

      - name: Write final-data.json to output
        id: write_output
        shell: python
        run: |
          #!/usr/bin/env python3

          import os
          import json

          GITHUB_OUTPUT = os.getenv('GITHUB_OUTPUT')

          with open('final-data.json', 'r') as data_file:
            data = json.load(data_file)

          with open(GITHUB_OUTPUT, 'w') as output_file:
            escaped_data = json.dumps(data).replace('"', '\"')
            output_file.write(f'data={escaped_data}')

  publish:
    needs: data_handler
    strategy:
      fail-fast: false
      matrix:
        year: [ 2025, 2026 ]
        prerelease: [ true, false ]
    uses: ./.github/workflows/tmodloader-publish.yml
    secrets: inherit
    with:
      version: ${{ fromJson(needs.data_handler.outputs.data).year[matrix.year].prerelease[matrix.prerelease] }}
      year: ${{ matrix.year }}
      prerelease: ${{ matrix.prerelease }}

